# docs: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # docs: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1

jobs:
  build:
    docker:
      # images: https://circleci.com/developer/images/image/cimg/node
      - image: cimg/node:15.1
    steps:
      - checkout
      # install and auto-cache packages
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test -- --coverage

# steps TODO:
# npm run docs
# npm run build
# npm run build:ff
# deploy pages
# publish release at Github (tags only)
# push release to store (tags only)

workflows:
  # docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  sample:
    jobs:
      - build
